# This is a basic workflow to help you get started with Actions

name: Modulo 5 CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: ckeckout
        uses: actions/checkout@v4
        #setup nodejs
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with: 
          node-version: "18"
      #install dependencies
      - name: install deps
        run: npm i
      #run build
      - name: Build app bundle
        run: npm run build
      #deploy to githpages
      - name: Deploy to pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          build_dir: dist/startkit
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
      
          
